language: node_js
node_js:
        - "6"
cache:
        - node_modules
dist: trusty
before_install: npm install mocha

after_success:
    - ./node_modules/.bin/nyc report --reporter=text-lcov > ./coverage/coverage.lcov && ./node_modules/.bin/codecov

before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3
